# Generated by Django 2.2.6 on 2019-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico_custom_sub', '__latest__'),
        ('juntagrico', '__latest__')
    ]

    operations = [
        migrations.CreateModel(
            name='DepotlistView',
            fields=[
                ('depot', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Depot')),
                ('wochentag', models.IntegerField(verbose_name='Wochentag')),
                ('fruchtjoghurt', models.IntegerField(verbose_name='Fruchtjoghurt')),
                ('naturejoghurt', models.IntegerField(verbose_name='naturejoghurt')),
                ('quark', models.IntegerField(verbose_name='Quark')),
                ('rohmilch', models.IntegerField(verbose_name='Rohmilch')),
                ('wochenkaese_gross_1', models.IntegerField(verbose_name='Wochenkäse gross 1')),
                ('wochenkaese_gross_2', models.IntegerField(verbose_name='Wochenkäse gross 2')),
                ('wochenkaese_klein', models.IntegerField(verbose_name='Wochenkäse klein')),
                ('zusatzkaese', models.IntegerField(verbose_name='Zusatzkäse')),
            ],
            options={
                'db_table': 'depotlist_view',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            sql="""CREATE OR REPLACE VIEW depotlist_view as
                WITH overview as (
                select depot.name as depot, depot.weekday as wochentag, 
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Fruchtjoghurt') as "fruchtjoghurt",
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Naturejoghurt') as "naturejoghurt",
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Quark') as "quark",
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Rohmilch') as "rohmilch",
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Wochenkäse gross') as "wochenkaese_gross_1",
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Wochenkäse gross') as "wochenkaese_gross_2",
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Wochenkäse klein') as "wochenkaese_klein",
                	sum(sub_content_item.amount) FILTER (WHERE product.name = 'Zusatzkäse') as "zusatzkaese"
                	from juntagrico_depot as depot
                	left join juntagrico_subscription as sub on depot.id = sub.depot_id
                	left join juntagrico_custom_sub_subscriptioncontent as sub_content on sub.billable_ptr_id = sub_content.subscription_id
                	left join juntagrico_custom_sub_subscriptioncontentitem as sub_content_item on sub_content_item.subscription_content_id = sub_content.id
                	left join juntagrico_custom_sub_product as product on product.id = sub_content_item.product_id
                	group by depot.name, wochentag
                )

                SELECT * FROM overview
                union all
                select
                'Total Freitag',
                null,
                sum(dl.fruchtjoghurt),
                sum(dl.naturejoghurt),
                sum(dl.quark),
                sum(dl.rohmilch),
                sum(dl."wochenkaese_gross_1"), 
                sum(dl."wochenkaese_gross_2"), 
                sum(dl."wochenkaese_klein"), 
                sum(dl.zusatzkaese)
                from overview as dl where dl.wochentag = 5
                union all
                select
                'Total Samstag',
                null,
                sum(dl.fruchtjoghurt),
                sum(dl.naturejoghurt),
                sum(dl.quark),
                sum(dl.rohmilch),
                sum(dl."wochenkaese_gross_1"),
                sum(dl."wochenkaese_gross_2"), 
                sum(dl."wochenkaese_klein"), 
                sum(dl.zusatzkaese)
                from overview as dl where wochentag = 6
                union all
                select
                'Total Woche',
                null,
                sum(dl.fruchtjoghurt),
                sum(dl.naturejoghurt),
                sum(dl.quark),
                sum(dl.rohmilch),
                sum(dl."wochenkaese_gross_1"),
                sum(dl."wochenkaese_gross_2"), 
                sum(dl."wochenkaese_klein"), 
                sum(dl.zusatzkaese)
                from overview as dl
                order by wochentag, depot;
            """,
            reverse_sql="""DROP VIEW IF EXISTS depotlist_view"""
        ),
    ]
