# Generated by Django 4.2.20 on 2025-04-20 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS juntagrico_polling_vote;
            DROP TABLE IF EXISTS juntagrico_polling_poll;
            """
        ),
    ]
